server:
  port: ${SERVER_PORT:8081}
spring:
  cloud:
    config:
      server:
        git:
          uri: ${REPO_CONFIG_FILES:https://github.com/jesus0508/configuration-files.git}
          search-paths: /{application}
          default-label: develop

  security:
    user:
      name: ${CLIENT_USER:user}
      password: ${CLIENT_PWD:s3cr3t}